name: Mineconomy-Core
version: '${version}'
main: nekonic.Main
api-version: '1.21.1'
author: Nekonic
description: "Mineconomy-Core 플러그인 - 경제, 은행, 주식 기능을 관리하는 핵심 플러그인"

commands:
  mark:
    description: "Mark 관련 명령어"
  name:
    description: "Name을 특정한 ID로 대체하는 명령어"
  stock:
    description: "Stock 관련 명령어"